<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('test',function(){
		dd(\Smart::getAllGatewaies());
		dd(\Smart::getAllCurrentDevices());
		dd(app('common')->DevSceneRepo()->startMutiControlRequest(1));
		dd(curl_post("https://api.ilifesmart.com/app/auth.RegisterUser",[]));
		dd(time());
		return app('common')->downloadImage('http://newnews.book.kaimusoft.xyz/uploads/logo.png');
});


//自动生成api文档
Route::group(['prefix' => 'swagger'], function () {
    Route::get('json', 'SwaggerController@getJSON');

});

Route::group(['prefix'=>'smart_data','namespace'=>'Smart'],function(){
	//前端路由
	Route::get('/', 'MainController@index');
});

//前端路由
Route::get('/', function(){
	// return redirect('/smart');
});

Route::get('/post/{id}','Smart\MainController@post');

//管理员
Route::group([ 'prefix' => 'smart'], function () {
	Route::get('login', 'Auth\AdminAuthController@showLoginForm');
	Route::post('login', 'Auth\AdminAuthController@login');
	Route::get('logout', 'Auth\AdminAuthController@logout');
});

/**
 *后台
 */

//后台ajax
Route::group(['prefix' => 'ajax'], function () {
		//文件上传
		Route::post('uploads', 'AppBaseController@uploads');
		//自动从excel中读取信息并且生成data
		Route::get('auto_generate_chartdata','AppBaseController@autoGenerateData');
});

//刷新缓存
Route::post('/clearCache','AppBaseController@clearCache');

Route::group(['middleware' => ['web', 'auth.admin'],'prefix'=>'smart','namespace'=>"Smart"],function(){
	//说明文档
	Route::get('/doc', 'SettingController@settingDoc');
	//后台首页
	Route::get('/', 'SettingController@setting');
	 //系统设置
    Route::get('settings/setting', 'SettingController@setting')->name('settings.setting');
    Route::post('settings/setting', 'SettingController@update')->name('settings.setting.update');
	//灯泡管理
	Route::resource('devLights', 'DevLightController');
	//地区管理
	Route::resource('regions', 'RegionController');
	//场景管理
	Route::resource('devScenes', 'DevSceneController');
	//场景关联的控制命令管理
	Route::resource('devCommands', 'DevCommandController');
	//传感器管理
	Route::resource('devSensors', 'DevSensorController');
	//窗帘电机
	Route::resource('devCurtains', 'DevCurtainController');
	//智能门锁设备管理
	Route::resource('devDoorLocks', 'DevDoorLockController');
	//门锁用户管理
	Route::resource('users', 'UserController');
	//设备数据管理
	 Route::resource('devIdxDays', 'DevIdxDayController');
	//用户偏好设置
	//Route::resource('preferences', 'PreferenceController');
	//图表数据管理
	Route::resource('chartDatas', 'ChartDataController');
	//网关设备管理
	Route::resource('gatewayDevs', 'GatewayDevController');
	//网关智慧中心管理
	Route::resource('gateways', 'GatewayController');
	//分类管理
	Route::resource('cats', 'CatController');
	//文章管理
	Route::resource('posts', 'PostController');
});



















