<?php

namespace App\Http\Controllers;

use InfyOm\Generator\Utils\ResponseUtil;
use Response;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Input;
use Illuminate\Http\Request;

class AppBaseController extends Controller
{
    public function sendResponse($result, $message)
    {
        return Response::json(ResponseUtil::makeResponse($message, $result));
    }

    public function sendError($error, $code = 404)
    {
        return Response::json(ResponseUtil::makeError($error), $code);
    }

    /**
     * 清空缓存
     * @return [type] [description]
     */
    public function clearCache()
    {
        Artisan::call('cache:clear');
        return ['status'=>true,'msg'=>''];
    }

    /**
     * 上传文件
     * @return [type] [description]
     */
    public function uploads()
    {
        $file =  Input::file('file');
        return app('common')->uploadFiles($file);
    }

     /**
     * [读取Excel信息并且生成chartdata]
     * @return [type] [description]
     */
    public function autoGenerateData(Request $request){
        $input = $request->all();
        return app('common')->generateChartData($input['excel_path'],$input);
    }

    //关闭场景及设备
    public function closeAllSceneAndDev(Request $request)
    {
        \Smart::closeAllSceneAndDev();
        return zcjy_callback_data('关闭成功',0,'web');
    }

    //触发用户的偏好场景
    public function triggerUserMutiScenes($user_id)
    {
        \Smart::triggerUserMutiScenes($user_id);
        return zcjy_callback_data('触发场景成功',0,'web');
    }
}
